### DISCUSSION TITLE
关于Windows系统的一些使用建议

### DISCUSSION THREAD

**Discussion by TommysLee** [PaddlePaddle/PaddleX#1849] [General]
百度飞浆AI一站式工具最新版PaddleX3的详细安装教程，根据以下步骤，可以帮助大家避坑，且一次性安装成功，助力大家将复杂的AI环境搭建标准化、流程化、简单化。原来AI开发可以如此简单。话不多说，直接上干货。

### 环境准备

本教程的PaddleX3环境搭建，基于此软硬件环境，请大家参考，如若您的环境与此不同，请尽量调整一致。

- 操作系统：**Windows 10/11 64位** 家庭版 / 专业版
- GPU：Nvidia （需支持**CUDA**）
- CUDA版本：**11.8**
- CUDNN版本：**8.9**
- Python版本：**3.10**

**注：请务必确认自己的Nvidia GPU是否支持CUDA11.8**

### 如何确认GPU是否支持CUDA11.8

- 打开NVIDIA控制面板后，点击左下角的 “系统信息”
- 在弹出的画面中，点击 “组件”   

![CUDA系统信息](https://github.com/user-attachments/assets/154504e1-c5c3-49dc-af3d-c5814aa43715)

**注：只要这里显示的CUDA版本号 ≥ 11.8 即可。**

### 安装步骤

严格按照下面的顺序流程，安装相关依赖与软件包，即可顺利完成PaddleX3的环境搭建。So Easy！

#### 1、安装Microsoft C++编译器

> [下载连接：https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/](https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/)

![Microsoft C++ 生成工具 - Visual Studio](https://github.com/user-attachments/assets/0175aba2-7652-47d9-8317-4751ef9fe865)

**注：此处下载的是在线安装包，所以安装过程较长，请耐心等待...**

> 在线安装包内部下载完安装包后，会弹出如下画面，请严格按如图**勾选相关配置，保持一致**。
>
> 否则在PaddleX编译时，会报错。（**这是第1个坑**）

![Microsoft C++生成工具安装选项设置](https://github.com/user-attachments/assets/4466d333-118b-403a-9c63-1754be0da136)

#### 2、安装CUDA 11.8

> [下载链接：https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local](https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local)

![CUDA Toolkit 11.8 Downloads](https://github.com/user-attachments/assets/362ae21d-95be-4e6a-b36b-d7988e8e7ea6)

- **双击安装，安装步骤如下图所示，相关选项，请与图中保持一致。**

![CUDA安装步骤1](https://github.com/user-attachments/assets/511583ed-4a40-40fd-a9df-0665c62d3f70)

![CUDA安装步骤2](https://github.com/user-attachments/assets/847d70d1-893e-4fbd-98a3-6084cada1087)

![CUDA安装步骤3](https://github.com/user-attachments/assets/05ef8f86-55e6-47e4-b237-0f26cd588584)

![CUDA安装步骤4](https://github.com/user-attachments/assets/bf98dc74-dead-4523-8243-d069451436e8)

> **重要提示：** 若电脑安装了360相关安全套件（如安全卫士、杀毒软件等），请在安装CUDA时，将其关闭，否则CUDA会安装失败。（**第2个坑**）

```shell
# 输入如下命令，验证CUDA是否安装成功
nvcc -V
 
# 输出如下内容，即安装成功
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

#### 3、安装CUDNN

> [下载链接：https://developer.nvidia.com/rdp/cudnn-archive](https://developer.nvidia.com/rdp/cudnn-archive)
>
> **注：下载cuDNN时，需要先登录Nvidia账号。**

![9](https://github.com/user-attachments/assets/ed2861c0-53c0-4f1b-8eff-d33ad74dc76b)

- **cuDNN安装非常简单，采用解压安装的方式；**
- **将下载的Zip压缩包，将其中的文件解压到CUDA安装的根目录，即安装完成。**

![cuDNN安装包内容](https://github.com/user-attachments/assets/3eb25a98-0a81-401b-a020-cd192a15bdfd)

#### 4、安装miniConda

> [下载链接：https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe](https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe)
>
> 注：点击链接下载最新版后，双击安装即可。

- **配置Conda国内源**

（1）生成配置文件 `.condarc` （其位置在用户根目录下）

```shell
conda config --set show_channel_urls yes
```

（2）将如下内容，复制到用户目录下的 `.condarc` 文件中

```yaml
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  deepmodeling: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/
```

（3）清除索引缓存，保证用的是镜像站提供的索引

```shell
conda clean -i
```

- **配置Pip国内源**

```shell
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
```

- **查询conda配置信息**

```shell
conda info
```

#### 5、基于miniConda创建Python环境

-  创建**python 3.10**环境，并将其命名为**paddlex**

```shell
conda create -n paddlex python==3.10
```

- 切换到paddlex环境

```shell
conda activate paddlex
```

#### 6、安装PaddlePaddle

```shell
python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/
```

使用以下命令可以验证 PaddlePaddle 是否安装成功。

```shell
python -c "import paddle; paddle.utils.run_check()"
```

查看 PaddlePaddle 版本的命令如下：

```shell
python -c "import paddle; print(paddle.__version__)"
```

如果安装成功，将输出如下内容：

```shell
3.0.0-beta1
```

##### 7-1、从 Github clone 源码

```shell
git clone -b release/3.0-beta https://github.com/PaddlePaddle/PaddleX.git
```

##### 7-2、安装配置及依赖

- 安装前置依赖，否则在编译paddlex时，会报权限错误（**第3个坑**）

```shell
cd PaddleX
 
# 安装依赖
python -m pip install --upgrade pip
pip install opencv-contrib-python==4.6.0.66 --user
```

- 安装 PaddleX whl

```shell
# -e：以可编辑模式安装，当前项目的代码更改，都会直接作用到已经安装的 PaddleX Wheel
pip install -e .
```

- 安装 PaddleX 相关依赖

```shell
# 安装命令
paddlex --install

# 国内用此命令加速
paddlex --install --platform gitee.com
```

- 完成安装后会有如下提示，表示PaddleX安装成功

```shell
All packages are installed.
```

### 使用PaddleX的模型进行AI推理

```shell
paddlex --pipeline object_detection \    
  --model PP-YOLOE_plus-S \    
  --input \    
  https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/fall.png
```

输出结果如下：

```
The device id has been set to 0.
Connecting to https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0/PP-YOLOE_plus-S_infer.tar ...
Downloading PP-YOLOE_plus-S_infer.tar ...
[==================================================] 100.00%
Extracting PP-YOLOE_plus-S_infer.tar
[==================================================] 100.00%
Transformation operators for data preprocessing will be inferred from config file.
Connecting to https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/fall.png ...
Downloading fall.png ...
[==================================================] 100.00%
The prediction result is:
[[   0.            0.965981    536.0723      565.9951     1624.9193
  1021.6263    ]
 [   0.            0.96458614  536.94745     131.15625    1133.9929
   874.8963    ]
 [   0.            0.9512729   161.86955      78.24556     537.0509
   935.6451    ]
 ...
 [  39.            0.01868815  437.38864     420.06418     535.0598
   497.7409    ]
 [  39.            0.01868636  543.26215     873.67395     619.9371
   939.1802    ]
 [  65.            0.01868468  450.03323     419.4944      490.1303
   443.73993   ]]
```

至此，PaddleX完全安装完毕！

Enjoy It！
