### ISSUE TITLE
PPYOLOE+的模型，预测时不管用什么图片来预测，都只有一个标签的结果

### ISSUE THREAD

**Issue by CashBai** [PaddlePaddle/PaddleX#2343]
训练时分pink、black、blue，3个种类的标签，最终训练结果map接近100%。
部署过后predict的结果不管用什么照片，只有black一种标签
![image](https://github.com/user-attachments/assets/2b36d317-7bca-4b9b-946a-ae0cbf31cf71)
![image](https://github.com/user-attachments/assets/2b787a90-5dcc-4378-90dc-7c7ced8170b0)

**Comment by cuicheng01** [comment]
可以看一下导出的模型对应的yml是真么样子的吗？

**Comment by CashBai** [comment]
@cuicheng01 
mode: paddle
draw_threshold: 0.1
metric: COCO
use_dynamic_shape: false
Pipeline:
  model: F:\Bai\HB_Workspace_Det\CCD2\model\21\inference
  batch_size: 1
Global:
  pipeline_name: object_detection
  model_name: PP-YOLOE_plus-L
arch: YOLO
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
  - 800
  - 224
  type: Resize
- mean:
  - 0.0
  - 0.0
  - 0.0
  norm_type: none
  std:
  - 1.0
  - 1.0
  - 1.0
  type: NormalizeImage
- type: Permute
label_list:
- pink
- black
- blue
Hpi:
  backend_config:
    openvino:
      cpu_num_threads: 8
    paddle_infer:
      cpu_num_threads: 8
      enable_log_info: false
    paddle_tensorrt:
      dynamic_shapes:
        im_shape:
        - - 1
          - 2
        - - 1
          - 2
        - - 1
          - 2
        image:
        - &id001
          - 1
          - 3
          - 800
          - 224
        - *id001
        - *id001
        scale_factor:
        - - 1
          - 2
        - - 1
          - 2
        - - 1
          - 2
      enable_log_info: false
      max_batch_size: 1
  selected_backends:
    cpu: openvino
    gpu: paddle_tensorrt
  supported_backends:
    cpu:
    - paddle_infer
    - openvino
    gpu:
    - paddle_infer
    - paddle_tensorrt

**Comment by ysyuann** [comment]
您好，这边刚才用同样的模型进行了训练和推理，没有发现相同的问题。能麻烦您给一下执行训练及推理时的命令以及训练时指定的output路径下保存的config.yml文件吗

**Comment by CashBai** [comment]
@lunaticsst 
训练时的命令：
`python main.py -c paddlex/configs/object_detection/PP-YOLOE_plus-L.yaml -o Global.mode=train -o Global.dataset_dir=F:/Bai/HB_Workspace_Det/CCD2/dataset/COCO3 -o Global.output=F:/Bai/HB_Workspace_Det/CCD2/model -o Evaluate.weight_path=F:/Bai/HB_Workspace_Det/CCD2/model/best_model/best_model.pdparams -o Train.num_classes=3`

config.yml文件：
```
CSPResNet:
  channels:
  - 64
  - 128
  - 256
  - 512
  - 1024
  layers:
  - 3
  - 6
  - 6
  - 3
  return_idx:
  - 1
  - 2
  - 3
  use_alpha: true
  use_large_stem: true
CustomCSPPAN:
  act: swish
  block_num: 3
  out_channels:
  - 768
  - 384
  - 192
  spp: true
  stage_num: 1
EvalDataset:
  allow_empty: true
  anno_path: annotations/instance_val.json
  dataset_dir: F:\Bai\HB_Workspace_Det\CCD2\dataset\COCO3
  image_dir: images
  name: COCODetDataset
EvalReader:
  batch_size: 2
  sample_transforms:
  - Decode: {}
  - Resize:
      interp: 2
      keep_ratio: false
      target_size:
      - 800
      - 224
  - NormalizeImage:
      mean:
      - 0.0
      - 0.0
      - 0.0
      norm_type: none
      std:
      - 1.0
      - 1.0
      - 1.0
  - Permute: {}
LearningRate:
  base_lr: 5.0e-05
  schedulers:
  - max_epochs: 96
    name: CosineDecay
  - name: LinearWarmup
    start_factor: 0.0
    steps: 100
OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
PPYOLOEHead:
  assigner:
    alpha: 1.0
    beta: 6.0
    name: TaskAlignedAssigner
    topk: 13
  fpn_strides:
  - 32
  - 16
  - 8
  grid_cell_offset: 0.5
  grid_cell_scale: 5.0
  loss_weight:
    class: 1.0
    dfl: 0.5
    iou: 2.5
  nms:
    keep_top_k: 300
    name: MultiClassNMS
    nms_threshold: 0.7
    nms_top_k: 1000
    score_threshold: 0.01
  static_assigner:
    name: ATSSAssigner
    topk: 9
  static_assigner_epoch: 30
  use_varifocal_loss: true
TestDataset: !ImageFolder
  anno_path: annotations/instance_val.json
  dataset_dir: F:\Bai\HB_Workspace_Det\CCD2\dataset\COCO3
  image_dir: ''
  sample_num: -1
  use_default_label: null
TestReader:
  batch_size: 1
  inputs_def:
    image_shape:
    - 3
    - 800
    - 224
  sample_transforms:
  - Decode: {}
  - Resize:
      interp: 2
      keep_ratio: false
      target_size:
      - 800
      - 224
  - NormalizeImage:
      mean:
      - 0.0
      - 0.0
      - 0.0
      norm_type: none
      std:
      - 1.0
      - 1.0
      - 1.0
  - Permute: {}
TrainDataset:
  anno_path: annotations/instance_train.json
  data_fields:
  - image
  - gt_bbox
  - gt_class
  - is_crowd
  dataset_dir: F:\Bai\HB_Workspace_Det\CCD2\dataset\COCO3
  image_dir: images
  name: COCODetDataset
TrainReader:
  batch_size: 4
  batch_transforms:
  - NormalizeImage:
      mean:
      - 0.0
      - 0.0
      - 0.0
      norm_type: none
      std:
      - 1.0
      - 1.0
      - 1.0
  - Permute: {}
  - PadGT: {}
  collate_batch: true
  drop_last: true
  sample_transforms:
  - Decode: {}
  - Resize:
      interp: 2
      keep_ratio: false
      target_size:
      - 800
      - 224
  shuffle: true
  use_shared_memory: true
YOLOv3:
  backbone: CSPResNet
  neck: CustomCSPPAN
  post_process: null
  yolo_head: PPYOLOEHead
amp: false
architecture: YOLOv3
custom_black_list:
- reduce_mean
depth_mult: 1.0
ema_black_list:
- proj_conv.weight
ema_decay: 0.9998
enable_ce: false
epoch: 30
eval: true
eval_height: 800
eval_size:
- 800
- 224
eval_width: 224
export:
  benchmark: false
  fuse_conv_bn: false
  nms: true
  post_process: true
filename: detmodel_PP-YOLOE_plus-L
find_unused_parameters: false
fleet: false
hpi_config_path: C:/Paddle/PaddleX-release-3.0-beta1/paddlex/utils/hpi_configs/PP-YOLOE_plus-L.yaml
log_iter: 10
metric: COCO
norm_type: sync_bn
num_classes: 3
pdx_model_name: PP-YOLOE_plus-L
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_crn_l_obj365_pretrained.pdparams
print_flops: false
print_params: false
profiler_options: null
proposals_path: sniper/proposals.json
resume: null
save_dir: F:\Bai\HB_Workspace_Det\CCD2\model
save_prediction_only: false
save_proposals: false
snapshot_epoch: 1
to_static: false
uniform_output_enabled: true
use_ema: true
use_gpu: true
use_mlu: false
use_npu: false
use_vdl: true
use_wandb: false
use_xpu: false
vdl_log_dir: F:\Bai\HB_Workspace_Det\CCD2\model
width_mult: 1.0
worker_num: 4
```

**Comment by ysyuann** [comment]
麻烦也给下完整的推理命令

**Comment by CashBai** [comment]
@lunaticsst 
完整的推理过程截图：
![image](https://github.com/user-attachments/assets/c8f01715-8e25-4ea6-948e-5b1dd317cd25)

**Comment by CashBai** [comment]
通过百度网盘分享的文件：COCO3.zip
链接：https://pan.baidu.com/s/1iyX0T3DpwgcWSMgV8HCFVQ?pwd=1jai 
提取码：1jai 

数据集我上传了，方便的话可以帮忙看一下

**Comment by ysyuann** [comment]
这边看到推理命令应该是不正确的，可以参照https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/module_usage/tutorials/cv_modules/object_detection.md 的4.4.1部分的推理代码，将配置路径和模型及图片路径做相应的修改进行推理看看是否有问题

**Comment by ysyuann** [comment]
这样推理还会出现相同的问题吗

**Comment by CashBai** [comment]
![image](https://github.com/user-attachments/assets/ba41e6c2-bce2-43e5-98eb-bf20281c27ca)
```
{
    "input_path": "F:\\Bai\\HB_Workspace_Det\\CCD2\\dataset\\COCO3\\images\\A01_0001.jpg",
    "boxes": [
        {
            "cls_id": 1,
            "label": "black",
            "score": 1.0,
            "coordinate": [
                606.916748046875,
                550.551025390625,
                2905,
                711
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.9999998807907104,
            "coordinate": [
                0,
                554.1034545898438,
                2905,
                711
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.9999831914901733,
            "coordinate": [
                0,
                552.9769897460938,
                2905,
                711
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.9998347759246826,
            "coordinate": [
                0,
                526.085205078125,
                2905,
                711
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.9982665777206421,
            "coordinate": [
                502.1681213378906,
                195.6964569091797,
                2905,
                405.22943115234375
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.997491717338562,
            "coordinate": [
                0,
                191.93997192382812,
                2905,
                429.5321960449219
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.9929909706115723,
            "coordinate": [
                0,
                194.63519287109375,
                2905,
                387.8458557128906
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.9895197153091431,
            "coordinate": [
                0,
                237.53497314453125,
                2905,
                454.2593994140625
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.9855567812919617,
            "coordinate": [
                0,
                494.93853759765625,
                2905,
                696.5199584960938
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.9835382103919983,
            "coordinate": [
                0,
                190.83773803710938,
                2905,
                409.34698486328125
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.9346230030059814,
            "coordinate": [
                0,
                540.3729858398438,
                2905,
                708.9473266601562
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.894672155380249,
            "coordinate": [
                0,
                495.3108825683594,
                2905,
                711
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.8845344185829163,
            "coordinate": [
                0,
                641.119384765625,
                2905,
                711
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.8479544520378113,
            "coordinate": [
                0,
                43.2921028137207,
                2905,
                368.8980712890625
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.8076444268226624,
            "coordinate": [
                0,
                211.67442321777344,
                2905,
                404.09716796875
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.7928148508071899,
            "coordinate": [
                0,
                463.5235290527344,
                2905,
                644.7340087890625
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.7521898746490479,
            "coordinate": [
                0,
                277.2778015136719,
                2905,
                443.6712951660156
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.7284709811210632,
            "coordinate": [
                0,
                395.8817138671875,
                2905,
                620.4560546875
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.7253029942512512,
            "coordinate": [
                0,
                309.314453125,
                2905,
                506.240966796875
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.7147154211997986,
            "coordinate": [
                0,
                336.3570251464844,
                2905,
                569.4330444335938
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.6736328601837158,
            "coordinate": [
                0,
                12.783212661743164,
                2905,
                333.05072021484375
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.6147423386573792,
            "coordinate": [
                0,
                0,
                2905,
                225.31394958496094
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.543666422367096,
            "coordinate": [
                0,
                245.77853393554688,
                2905,
                411.562255859375
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.4384709894657135,
            "coordinate": [
                0,
                285.2864685058594,
                2905,
                473.7020568847656
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.42254677414894104,
            "coordinate": [
                0,
                426.5365905761719,
                2905,
                604.2317504882812
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.2490214705467224,
            "coordinate": [
                0,
                178.14804077148438,
                2905,
                351.9794006347656
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.24551507830619812,
            "coordinate": [
                0,
                177.4586944580078,
                2905,
                349.6714782714844
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.2080455720424652,
            "coordinate": [
                0,
                254.2236328125,
                2905,
                445.5656433105469
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.20280729234218597,
            "coordinate": [
                0,
                594.5457763671875,
                2905,
                710.2747802734375
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.17615076899528503,
            "coordinate": [
                0,
                50.60137176513672,
                2905,
                247.34751892089844
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.17344360053539276,
            "coordinate": [
                0,
                557.5133666992188,
                2905,
                711
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.1664094477891922,
            "coordinate": [
                0,
                4.427862167358398,
                2905,
                187.0993194580078
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.14659498631954193,
            "coordinate": [
                0,
                373.7319030761719,
                2905,
                578.22802734375
            ]
        },
        {
            "cls_id": 1,
            "label": "black",
            "score": 0.11924007534980774,
            "coordinate": [
                0,
                578.9500122070312,
                2905,
                711
            ]
        }
    ]
}
```

结果还是不太对，和我python里的预测结果一样，这张图片应该是pink的，训练结果map都99%了，理论上不应该只有black的预测结果。和我修改的Reader有关吗？
我修改了C:\Paddle\PaddleX-release-3.0-beta1\paddlex\repo_apis\PaddleDetection_api\configs\PP-YOLOE_plus-L.yaml
```
# Runtime
epoch: 10
log_iter: 10
find_unused_parameters: false
use_gpu: true
use_xpu: false
use_mlu: false
use_npu: false
use_ema: True
save_dir: output
snapshot_epoch: 1
print_flops: false
print_params: false

# Dataset
metric: COCO
num_classes: 80

worker_num: 4
eval_height: &eval_height 800
eval_width: &eval_width 224
eval_size: &eval_size [*eval_height, *eval_width]

TrainDataset:
  name: COCODetDataset
  image_dir: images
  anno_path: annotations/instance_train.json
  dataset_dir: datasets/COCO
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODetDataset
  image_dir: images
  anno_path: annotations/instance_val.json
  dataset_dir: datasets/COCO
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/instance_val.json
  dataset_dir: datasets/COCO

TrainReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
  batch_transforms:
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
    - PadGT: {}
  batch_size: 8
  shuffle: true
  drop_last: true
  use_shared_memory: true
  collate_batch: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 2

TestReader:
  inputs_def:
    image_shape: [3, *eval_height, *eval_width]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1

# Model
architecture: YOLOv3
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_crn_l_obj365_pretrained.pdparams

norm_type: sync_bn
ema_decay: 0.9998
ema_black_list: ['proj_conv.weight']
custom_black_list: ['reduce_mean']
depth_mult: 1.0
width_mult: 1.0

YOLOv3:
  backbone: CSPResNet
  neck: CustomCSPPAN
  yolo_head: PPYOLOEHead
  post_process: ~

CSPResNet:
  layers: [3, 6, 6, 3]
  channels: [64, 128, 256, 512, 1024]
  return_idx: [1, 2, 3]
  use_large_stem: true
  use_alpha: True

CustomCSPPAN:
  out_channels: [768, 384, 192]
  stage_num: 1
  block_num: 3
  act: 'swish'
  spp: true

PPYOLOEHead:
  fpn_strides: [32, 16, 8]
  grid_cell_scale: 5.0
  grid_cell_offset: 0.5
  static_assigner_epoch: 30
  use_varifocal_loss: true
  loss_weight: {class: 1.0, iou: 2.5, dfl: 0.5}
  static_assigner:
    name: ATSSAssigner
    topk: 9
  assigner:
    name: TaskAlignedAssigner
    topk: 13
    alpha: 1.0
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 300
    score_threshold: 0.01
    nms_threshold: 0.7

# Optimizer
LearningRate:
  base_lr: 0.0001
  schedulers:
    - name: CosineDecay
      max_epochs: 96
    - name: LinearWarmup
      start_factor: 0.
      steps: 100

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

# Export
export:
  post_process: true
  nms: true
  benchmark: false
  fuse_conv_bn: false

```
