### ISSUE TITLE
Paddlex安装hpi以后调用PP_StructureV3报错

### ISSUE THREAD

**Issue by snow-swallow** [PaddlePaddle/PaddleX#4184]
## Checklist:

- [X] 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
- [X] 翻阅[FAQ](https://paddlepaddle.github.io/PaddleX/main/FAQ.html)
- [X] 翻阅[PaddleX 文档](https://paddlepaddle.github.io/PaddleX/main/index.html)
- [X] 确认bug是否在新版本里还未修复

## 描述问题

1. 使用docker镜像部署在ks中
 
镜像信息：
```
[paddle:3.0.0-gpu-cuda11.8-cudnn8.9-trt8.6](http://ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle:3.0.0-gpu-cuda11.8-cudnn8.9-trt8.6)
```

显卡信息
```
Fri Jun 13 02:52:02 2025
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.230.02             Driver Version: 535.230.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A40                     Off | 00000000:AF:00.0 Off |                    0 |
|  0%   41C    P0              78W / 300W |   6397MiB / 46068MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

2. 版面分析执行的命令: 

```
paddlex --pipeline  PP-StructureV3  --input   https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/demo_paper.png --use_hpip
```

3. 报错

```
File "/root/PaddleX/paddlex/inference/models/image_classsification/predictor.py", line 49, in _ init
self.preprocessors, self.infer, self.postprocessors= self._build()
File "/root/PaddleX/paddlex/inference/models/image_classification/predictor.py",line 82, in _build
infer= self.create_static_infer()
/return HPInfer(
File "/root/Paddlex/paddlex/inference/models/base/predictor/base_predictorin create_static_infer
File "/root/PaddleX/paddlex/utils/deps.py", line 148, in _ rapper
return old_init_func(self, *args, **kwargs)
File "/root/PaddleX/paddlex/inference/models/common/static_iinfer.py",line 575, in in init_
File "/root/PaddleX/paddlex/inference/models/common/static_infer.py", line 630, in _determine_backend_config
backend, backend_config = self._determine_backend_and_config()
raise RuntimeError(
RuntimeError: No inference backend and confiauration could be suggested, Reason: "PP-LCNJet x1 0 textline ori' is not a known model.
```

**Comment by cuicheng01** [comment]
您好，我们定位到了问题，应该是有一处PR没有正确cherry-pick导致的，我们会在3.0.2修复

**Comment by Bobholamovic** [comment]
你好，这是PaddleX 3.0.1的一个bug，我们预计将在下个版本解决。目前，请尝试如下步骤绕过这个问题：

1. 执行 `paddlex --get_pipeline_config PP-StructureV3` 获取产线配置文件（按回车）；
2. 修改产线配置文件，找到两处`TextLineOrientation`，增加如下配置：

    ```yaml
    TextLineOrientation:
        ...
        use_hpip: False
    ``` 
3. 启动服务：`paddlex --pipeline  PP-StructureV3.yaml  --input   https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/demo_paper.png --use_hpip`

**Comment by snow-swallow** [comment]
你好，我这的TextLineOrientation配置看起来本身就是没有启用hpi，下面是执行`paddlex --get_pipeline_config PP-StructureV3 ` 后的输出。 那我还需要加上`use_hpip: False` 吗? 另外还有一个问题，我这边还对比写了下普通的image classification速度，似乎和官方paddle-ocr的执行速度差不多，我没有太大信心是否正确启用了hpi。请问是否有什么指令可以确认下我的环境的安装情况吗？

```
pipeline_name: PP-StructureV3

batch_size: 8

use_doc_preprocessor: True
use_seal_recognition: True
use_table_recognition: True
use_formula_recognition: True
use_chart_recognition: True
use_region_detection: True

SubModules:
  LayoutDetection:
    module_name: layout_detection
    model_name: PP-DocLayout_plus-L
    model_dir: null
    batch_size: 8
    threshold: 
      0: 0.3  # paragraph_title
      1: 0.5  # image
      2: 0.4  # text
      3: 0.5  # number
      4: 0.5  # abstract
      5: 0.5  # content
      6: 0.5  # figure_table_chart_title
      7: 0.3  # formula
      8: 0.5  # table
      9: 0.5  # reference
      10: 0.5 # doc_title
      11: 0.5 # footnote
      12: 0.5 # header
      13: 0.5 # algorithm
      14: 0.5 # footer
      15: 0.45 # seal
      16: 0.5 # chart
      17: 0.5 # formula_number
      18: 0.5 # aside_text
      19: 0.5 # reference_content
    layout_nms: True
    layout_unclip_ratio: [1.0, 1.0] 
    layout_merge_bboxes_mode: 
      0: "large"  # paragraph_title
      1: "large"  # image
      2: "union"  # text
      3: "union"  # number
      4: "union"  # abstract
      5: "union"  # content
      6: "union"  # figure_table_chart_title
      7: "large"  # formula
      8: "union"  # table
      9: "union"  # reference
      10: "union" # doc_title
      11: "union" # footnote
      12: "union" # header
      13: "union" # algorithm
      14: "union" # footer
      15: "union" # seal
      16: "large" # chart
      17: "union" # formula_number
      18: "union" # aside_text
      19: "union" # reference_content
  ChartRecognition:
    module_name: chart_recognition
    model_name: PP-Chart2Table
    model_dir: null
    batch_size: 1 
  RegionDetection:
    module_name: layout_detection
    model_name: PP-DocBlockLayout
    model_dir: null
    layout_nms: True
    layout_merge_bboxes_mode: "small"

SubPipelines:
  DocPreprocessor:
    pipeline_name: doc_preprocessor
    batch_size: 8
    use_doc_orientation_classify: True
    use_doc_unwarping: True
    SubModules:
      DocOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: null
        batch_size: 8
      DocUnwarping:
        module_name: image_unwarping
        model_name: UVDoc
        model_dir: null

  GeneralOCR:
    pipeline_name: OCR
    batch_size: 8
    text_type: general
    use_doc_preprocessor: False
    use_textline_orientation: True
    SubModules:
      TextDetection:
        module_name: text_detection
        model_name: PP-OCRv5_server_det
        model_dir: null
        limit_side_len: 736
        limit_type: min
        max_side_limit: 4000
        thresh: 0.3
        box_thresh: 0.6
        unclip_ratio: 1.5
      TextLineOrientation:
        module_name: textline_orientation
        model_name: PP-LCNet_x0_25_textline_ori
        model_dir: null
        batch_size: 8
      TextRecognition:
        module_name: text_recognition
        model_name: PP-OCRv5_server_rec
        model_dir: null
        batch_size: 8
        score_thresh: 0.0


  TableRecognition:
    pipeline_name: table_recognition_v2
    use_layout_detection: False
    use_doc_preprocessor: False
    use_ocr_model: False
    SubModules:  
      TableClassification:
        module_name: table_classification
        model_name: PP-LCNet_x1_0_table_cls
        model_dir: null

      WiredTableStructureRecognition:
        module_name: table_structure_recognition
        model_name: SLANeXt_wired
        model_dir: null

      WirelessTableStructureRecognition:
        module_name: table_structure_recognition
        model_name: SLANet_plus
        model_dir: null

      WiredTableCellsDetection:
        module_name: table_cells_detection
        model_name: RT-DETR-L_wired_table_cell_det
        model_dir: null

      WirelessTableCellsDetection:
        module_name: table_cells_detection
        model_name: RT-DETR-L_wireless_table_cell_det
        model_dir: null

      TableOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: null
    SubPipelines:
      GeneralOCR:
        pipeline_name: OCR
        text_type: general
        use_doc_preprocessor: False
        use_textline_orientation: True
        SubModules:
          TextDetection:
            module_name: text_detection
            model_name: PP-OCRv5_server_det
            model_dir: null
            limit_side_len: 736
            limit_type: min
            max_side_limit: 4000
            thresh: 0.3
            box_thresh: 0.4
            unclip_ratio: 1.5
          TextLineOrientation:
            module_name: textline_orientation
            model_name: PP-LCNet_x0_25_textline_ori
            model_dir: null
            batch_size: 8
          TextRecognition:
            module_name: text_recognition
            model_name: PP-OCRv5_server_rec
            model_dir: null
            batch_size: 8
        score_thresh: 0.0

  SealRecognition:
    pipeline_name: seal_recognition
    batch_size: 8
    use_layout_detection: False
    use_doc_preprocessor: False
    SubPipelines:
      SealOCR:
        pipeline_name: OCR
        batch_size: 8
        text_type: seal
        use_doc_preprocessor: False
        use_textline_orientation: False
        SubModules:
          TextDetection:
            module_name: seal_text_detection
            model_name: PP-OCRv4_server_seal_det
            model_dir: null
            limit_side_len: 736
            limit_type: min
            max_side_limit: 4000
            thresh: 0.2
            box_thresh: 0.6
            unclip_ratio: 0.5
          TextRecognition:
            module_name: text_recognition
            model_name: PP-OCRv5_server_rec
            model_dir: null
            batch_size: 8
            score_thresh: 0

  FormulaRecognition:
    pipeline_name: formula_recognition
    batch_size: 8
    use_layout_detection: False
    use_doc_preprocessor: False
    SubModules:
      FormulaRecognition:
        module_name: formula_recognition
        model_name: PP-FormulaNet_plus-L
        model_dir: null
        batch_size: 8
```


另外，这是我环境中跟paddle相关的一些版本，FYI

```
paddle2onnx               2.0.2rc3
paddle3d                  0.0.0
paddleclas                2.6.0
paddledet                 0.0.0
paddlefsl                 1.1.0
paddlenlp                 2.8.0.post0
paddleocr                 3.0.0
paddlepaddle-gpu          3.0.0
paddleseg                 0.0.0.dev0
paddlets                  1.1.0
paddlex                   3.0.0
```
