### ISSUE TITLE
昆仑P800无法运行版面分析V3产线

### ISSUE THREAD

**Issue by Chenhb123** [PaddlePaddle/PaddleX#4266]
## Checklist:

- [ ] 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
- [ ] 翻阅[FAQ](https://paddlepaddle.github.io/PaddleX/main/FAQ.html)
- [ ] 翻阅[PaddleX 文档](https://paddlepaddle.github.io/PaddleX/main/index.html)
- [ ] 确认bug是否在新版本里还未修复

## 描述问题
您好，我在昆仑P800上测试版面分析V3产线时报错,我的运行命令是：
```bash
paddlex --pipeline PP-StructureV3-xpu.yaml  \
--input pp_structure_v3_demo.png \
--use_doc_orientation_classify False \
--use_doc_unwarping False \
--use_textline_orientation False \
--use_e2e_wireless_table_rec_model True \
--save_path ./output  --device xpu:0
```
报错日志为：
```bash
Creating model: ('UVDoc', None)
Using official model (UVDoc), the model files will be automatically downloaded and saved in official_models.
XCCL /usr/local/lib/python3.10/dist-packages/paddle/base/../libs/libbkcl.so loaded
[02:58:34][e9b7d63a92c0][54098][WARN][BKCL][globals.cpp:211] xccl version: d6202e5 [rdma] [bugfix for non-XDR mode] build data: Feb 10 2025 11:13:15
W0626 02:58:35.756794 54098 analysis_config.cc:227] Parameters in EnableXpu/enable_xpu is deprecated since version 2.6.1, and will be removed in version 3.0! Please use EnableXpu/enable_xpu without parameters, and use SetXpuConfig/set_xpu_config to set options.
Creating model: ('PP-DocBlockLayout', None)
Using official model (PP-DocBlockLayout), the model files will be automatically downloaded and saved in official_models.
Creating model: ('PP-DocLayout_plus-L', None)
Using official model (PP-DocLayout_plus-L), the model files will be automatically downloaded and saved in official_models.
Creating model: ('PP-OCRv4_mobile_det', None)
Using official model (PP-OCRv4_mobile_det), the model files will be automatically downloaded and saved in official_models.
Creating model: ('PP-OCRv4_mobile_rec', None)
Using official model (PP-OCRv4_mobile_rec), the model files will be automatically downloaded and saved in official_models.
Creating model: ('PP-OCRv4_mobile_seal_det', None)
Using official model (PP-OCRv4_mobile_seal_det), the model files will be automatically downloaded and saved in official_models.
Creating model: ('PP-OCRv4_mobile_rec', None)
Using official model (PP-OCRv4_mobile_rec), the model files will be automatically downloaded and saved in official_models.
Creating model: ('PP-LCNet_x1_0_table_cls', None)
Using official model (PP-LCNet_x1_0_table_cls), the model files will be automatically downloaded and saved in official_models.
Creating model: ('SLANeXt_wired', None)
Using official model (SLANeXt_wired), the model files will be automatically downloaded and saved in official_models.
Creating model: ('SLANeXt_wireless', None)
Using official model (SLANeXt_wireless), the model files will be automatically downloaded and saved in official_models.
Creating model: ('RT-DETR-L_wired_table_cell_det', None)
Using official model (RT-DETR-L_wired_table_cell_det), the model files will be automatically downloaded and saved in official_models.
Creating model: ('RT-DETR-L_wireless_table_cell_det', None)
Using official model (RT-DETR-L_wireless_table_cell_det), the model files will be automatically downloaded and saved in official_models.
Traceback (most recent call last):
  File "/usr/local/bin/paddlex", line 8, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.10/dist-packages/paddlex/__main__.py", line 26, in console_entry
    main()
  File "/usr/local/lib/python3.10/dist-packages/paddlex/paddlex_cli.py", line 467, in main
    pipeline_predict(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/paddlex_cli.py", line 328, in pipeline_predict
    for res in result:
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/_parallel.py", line 129, in predict
    yield from self._pipeline.predict(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/layout_parsing/pipeline_v2.py", line 1059, in predict
    layout_det_results = list(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/base/predictor/base_predictor.py", line 211, in __call__
    yield from self.apply(input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/base/predictor/base_predictor.py", line 267, in apply
    prediction = self.process(batch_data, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/object_detection/predictor.py", line 234, in process
    batch_preds = self.infer(batch_inputs)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/common/static_infer.py", line 287, in __call__
    pred = self.infer(x)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/common/static_infer.py", line 252, in __call__
    self.predictor.run()
OSError: In user code:


    ExternalError: pool2dXDNN Error <1>, XDNN_INVALID_PARAM  (at /paddle/paddle/phi/kernels/xpu/pool_kernel.cc:163)
      [operator < pd_kernel.phi_kernel > error]


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::memory::allocation::StreamSafeXPUAllocator::ReleaseImpl(phi::Place const&)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()
4   paddle::memory::allocation::XPUAllocator::FreeImpl(phi::Allocation*)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1750906729 (unix time) try "date -d @1750906729" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 54098 (TID 0x7fe88143b740) from PID 0 ***]
```

## 复现

1. 高性能推理

    * 您是否完全按照[高性能推理文档教程](https://paddlepaddle.github.io/PaddleX/main/pipeline_deploy/high_performance_inference.html)跑通了流程？

2. 服务化部署

    * 您是否完全按照[服务化部署文档教程](https://paddlepaddle.github.io/PaddleX/main/pipeline_deploy/serving.html)跑通了流程？

    * 您在服务化部署中是否有使用高性能推理插件？

    * 您使用了哪一种服务化部署方案？

    * 如果是多语言调用的问题，请给出调用示例子。

3. 端侧部署
    * 您是否完全按照[端侧部署文档教程](https://paddlepaddle.github.io/PaddleX/main/pipeline_deploy/on_device_deployment.html)跑通了流程？

    * 您使用的端侧设备是？对应的PaddlePaddle版本和PaddleLite版本分别是什么？

3. 您使用的**模型**和**数据集**是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号
版本信息如下：
```bash
python --version
Python 3.10.13

pip list installed | grep paddle
paddle2onnx            1.1.0
paddleclas             2.5.2
paddleocr              2.7.0.3
paddlepaddle-xpu       3.0.0
paddlex                3.0.0

```

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
使用官方镜像在容器中运行：
```bash
ccr-2vdh3abv-pub.cnc.bj.baidubce.com/device/paddle-xpu:3.0.0-xpu-ubuntu20-x86_64-gcc84-py310
```
3. 请问您使用的CUDA/cuDNN的版本号是？
xpu驱动版本号为：
```bash
xpu-smi -i 0
Thu Jun 26 03:05:05 2025       
+-----------------------------------------------------------------------------+
| XPU-SMI               Driver Version: 5.0.21.19    XPU-RT Version: 5.0.21   |
```

**Comment by a31413510** [comment]
切换到 develop 版本试试
pip install --pre paddlepaddle-xpu -i https://www.paddlepaddle.org.cn/packages/nightly/xpu-p800/

**Comment by Chenhb123** [comment]
> 切换到 develop 版本试试 pip install --pre paddlepaddle-xpu -i https://www.paddlepaddle.org.cn/packages/nightly/xpu-p800/

更新到3.1.1版本后可以运行成功：
```bash
pip list installed | grep paddle
paddle2onnx              1.1.0
paddleclas               2.5.2
paddleocr                2.7.0.3
paddlepaddle-xpu         3.0.0
paddlex                  3.1.1

paddlex --pipeline PP-StructureV3.yaml    \
     --input pp_structure_v3_demo.png     \
    --use_doc_orientation_classify False    \
     --use_doc_unwarping False     \
    --use_textline_orientation False    \
     --use_e2e_wireless_table_rec_model True     \
    --save_path ./output     \
    --device xpu:0
```

<img width="1576" height="597" alt="Image" src="https://github.com/user-attachments/assets/26f129c0-4607-49a8-bcca-f0c2f6af0740" />

我的yaml文件内容如下，跟您确认下目前只能加载基础的版面区域检测、文本检测/文本识别模型吗？
```yaml
pipeline_name: PP-StructureV3

batch_size: 8

use_doc_preprocessor: True
use_seal_recognition: False
use_table_recognition: False
use_formula_recognition: False
use_chart_recognition: False
use_region_detection: False

SubModules:
  LayoutDetection:
    module_name: layout_detection
    model_name: PicoDet_layout_1x
    model_dir: null
    batch_size: 8
    threshold: 
      0: 0.3  # paragraph_title
      1: 0.5  # image
      2: 0.4  # text
      3: 0.5  # number
      4: 0.5  # abstract
      5: 0.5  # content
      6: 0.5  # figure_table_chart_title
      7: 0.3  # formula
      8: 0.5  # table
      9: 0.5  # reference
      10: 0.5 # doc_title
      11: 0.5 # footnote
      12: 0.5 # header
      13: 0.5 # algorithm
      14: 0.5 # footer
      15: 0.45 # seal
      16: 0.5 # chart
      17: 0.5 # formula_number
      18: 0.5 # aside_text
      19: 0.5 # reference_content
    layout_nms: True
    layout_unclip_ratio: [1.0, 1.0] 
    layout_merge_bboxes_mode: 
      0: "large"  # paragraph_title
      1: "large"  # image
      2: "union"  # text
      3: "union"  # number
      4: "union"  # abstract
      5: "union"  # content
      6: "union"  # figure_table_chart_title
      7: "large"  # formula
      8: "union"  # table
      9: "union"  # reference
      10: "union" # doc_title
      11: "union" # footnote
      12: "union" # header
      13: "union" # algorithm
      14: "union" # footer
      15: "union" # seal
      16: "large" # chart
      17: "union" # formula_number
      18: "union" # aside_text
      19: "union" # reference_content
  ChartRecognition:
    module_name: chart_recognition
    model_name: PP-Chart2Table
    model_dir: null
    batch_size: 1 
  RegionDetection:
    module_name: layout_detection
    model_name: PP-DocBlockLayout
    model_dir: null
    layout_nms: True
    layout_merge_bboxes_mode: "small"

SubPipelines:
  DocPreprocessor:
    pipeline_name: doc_preprocessor
    batch_size: 8
    use_doc_orientation_classify: False
    use_doc_unwarping: False
    SubModules:
      DocOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: null
        batch_size: 8
      DocUnwarping:
        module_name: image_unwarping
        model_name: UVDoc
        model_dir: null

  GeneralOCR:
    pipeline_name: OCR
    batch_size: 8
    text_type: general
    use_doc_preprocessor: False
    use_textline_orientation: False
    SubModules:
      TextDetection:
        module_name: text_detection
        model_name: PP-OCRv4_server_det
        model_dir: null
        limit_side_len: 736
        limit_type: min
        max_side_limit: 4000
        thresh: 0.3
        box_thresh: 0.6
        unclip_ratio: 1.5
      TextLineOrientation:
        module_name: textline_orientation
        model_name: PP-LCNet_x1_0_textline_ori
        model_dir: null
        batch_size: 8
      TextRecognition:
        module_name: text_recognition
        model_name: PP-OCRv4_server_rec
        model_dir: null
        batch_size: 8
        score_thresh: 0.0
 

  TableRecognition:
    pipeline_name: table_recognition_v2
    use_layout_detection: False
    use_doc_preprocessor: False
    use_ocr_model: False
    SubModules:  
      TableClassification:
        module_name: table_classification
        model_name: PP-LCNet_x1_0_table_cls
        model_dir: null

      WiredTableStructureRecognition:
        module_name: table_structure_recognition
        model_name: SLANeXt_wired
        model_dir: null
      
      WirelessTableStructureRecognition:
        module_name: table_structure_recognition
        model_name: SLANeXt_wireless
        model_dir: null
      
      WiredTableCellsDetection:
        module_name: table_cells_detection
        model_name: RT-DETR-L_wired_table_cell_det
        model_dir: null
      
      WirelessTableCellsDetection:
        module_name: table_cells_detection
        model_name: RT-DETR-L_wireless_table_cell_det
        model_dir: null

      TableOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: null
    SubPipelines:
      GeneralOCR:
        pipeline_name: OCR
        text_type: general
        use_doc_preprocessor: False
        use_textline_orientation: False
        SubModules:
          TextDetection:
            module_name: text_detection
            model_name: PP-OCRv4_server_det
            model_dir: null
            limit_side_len: 736
            limit_type: min
            max_side_limit: 4000
            thresh: 0.3
            box_thresh: 0.4
            unclip_ratio: 1.5
          TextLineOrientation:
            module_name: textline_orientation
            model_name: PP-LCNet_x1_0_textline_ori
            model_dir: null
            batch_size: 8
          TextRecognition:
            module_name: text_recognition
            model_name: PP-OCRv4_server_rec
            model_dir: null
            batch_size: 8
        score_thresh: 0.0

  SealRecognition:
    pipeline_name: seal_recognition
    batch_size: 8
    use_layout_detection: False
    use_doc_preprocessor: False
    SubPipelines:
      SealOCR:
        pipeline_name: OCR
        batch_size: 8
        text_type: seal
        use_doc_preprocessor: False
        use_textline_orientation: False
        SubModules:
          TextDetection:
            module_name: seal_text_detection
            model_name: PP-OCRv4_server_seal_det
            model_dir: null
            limit_side_len: 736
            limit_type: min
            max_side_limit: 4000
            thresh: 0.2
            box_thresh: 0.6
            unclip_ratio: 0.5
          TextRecognition:
            module_name: text_recognition
            model_name: PP-OCRv4_server_rec
            model_dir: null
            batch_size: 8
            score_thresh: 0
    
  FormulaRecognition:
    pipeline_name: formula_recognition
    batch_size: 8
    use_layout_detection: False
    use_doc_preprocessor: False
    SubModules:
      FormulaRecognition:
        module_name: formula_recognition
        model_name: PP-FormulaNet_plus-L
        model_dir: null
        batch_size: 8

```
