### ISSUE TITLE
paddlex中PPYOLO的模型为什么只能下载到ppyolo_2x.pdparams，而没有model.yml和模型结构参数

### ISSUE THREAD

**Issue by xiaoQxiong** [PaddlePaddle/PaddleX#611]
问题类型：模型部署
**问题描述**  
paddlex 的预训练模式PPYOLO 为什么不是标准的model.yml __model__ __params__文件，而仅有一个pdparams
========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by jiangjiajun** [comment]
没有提供可直接使用的模型，当前提供的都是用于二次训练的预训练模型

**Comment by xiaoQxiong** [comment]
但是这样个人其实没有那么多显卡 导致batchsize 不能设置大，训练效果差 无法享受到 百度公布模型的性能

**Comment by jiangjiajun** [comment]
请直接手动保存如下的内容为model.yml，与pdparams放在同一个目录即可使用paddlex.load_model加载，如若要进一步进行部署，可使用`paddlex --export_model`命令进行导出，即可得到`__model__`、`__params__`和`model.yml`文件
```
Model: PPYOLO
Transforms:
- Resize:
    interp: CUBIC
    target_size: 608
- Normalize:
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
_Attributes:
  eval_metrics:
    bbox_map: 0.0
  fixed_input_shape: null
  labels:
  - person
  - bicycle
  - car
  - motorcycle
  - airplane
  - bus
  - train
  - truck
  - boat
  - traffic light
  - fire hydrant
  - stop sign
  - parking meter
  - bench
  - bird
  - cat
  - dog
  - horse
  - sheep
  - cow
  - elephant
  - bear
  - zebra
  - giraffe
  - backpack
  - umbrella
  - handbag
  - tie
  - suitcase
  - frisbee
  - skis
  - snowboard
  - sports ball
  - kite
  - baseball bat
  - baseball glove
  - skateboard
  - surfboard
  - tennis racket
  - bottle
  - wine glass
  - cup
  - fork
  - knife
  - spoon
  - bowl
  - banana
  - apple
  - sandwich
  - orange
  - broccoli
  - carrot
  - hot dog
  - pizza
  - donut
  - cake
  - chair
  - couch
  - potted plant
  - bed
  - dining table
  - toilet
  - tv
  - laptop
  - mouse
  - remote
  - keyboard
  - cell phone
  - microwave
  - oven
  - toaster
  - sink
  - refrigerator
  - book
  - clock
  - vase
  - scissors
  - teddy bear
  - hair drier
  - toothbrush
  model_type: detector
  num_classes: 80
_init_params:
  anchor_masks: null
  anchors: null
  backbone: ResNet50_vd_ssld
  ignore_threshold: 0.7
  input_channel: 3
  label_smooth: false
  nms_iou_threshold: 0.45
  nms_keep_topk: 100
  nms_score_threshold: 0.01
  nms_topk: 1000
  num_classes: 6
  scale_x_y: 1.05
  train_random_shapes:
  - 320
  - 352
  - 384
  - 416
  - 448
  - 480
  - 512
  - 544
  - 576
  - 608
  use_coord_conv: true
  use_drop_block: true
  use_iou_aware: true
  use_iou_loss: true
  use_matrix_nms: true
  use_spp: true
  with_dcn_v2: true
completed_epochs: 1
status: Normal
version: 1.3.4
```
